version: '2.4'
services:
  database:
    image: 'mysql:latest'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - '3306:3306'
    volumes:
      - './dump_updated.sql:/docker-entrypoint-initdb.d/dump.sql'
    networks:
      app:
        ipv4_address: 10.1.1.3
  nginx-fpm:
    image: 'richarvey/nginx-php-fpm:latest'
    volumes:
      - './src:/var/www/html'
      - './nginx.conf:/etc/nginx/nginx.conf'
    ports:
      - '80:80'
    environment:
      ENABLE_XDEBUG: 1
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      CI_ENV: ${CI_ENV}
      CI_APP_DIR: ${CI_APP_DIR}
      NGINX_SERVER_NAME: ${NGINX_SERVER_NAME}
    networks:
      app:
        ipv4_address: 10.1.1.2
networks:
  app:
    external: true